try:
    raise ValueError
except ValueError:
    print('There was an exception.')